import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Humanoid & Physical AI Robotics',
      link: {
        type: 'generated-index',
        slug: '/category/humanoid-physical-ai-robotics'
      },
      items: [
        'humanoid-physical-ai/introduction',
        'humanoid-physical-ai/evolution-of-humanoids',
        'humanoid-physical-ai/physical-ai-vs-software-ai',
        'humanoid-physical-ai/body-architecture',
        'humanoid-physical-ai/sensors-and-perception',
        'humanoid-physical-ai/actuators-and-motion',
        'humanoid-physical-ai/ai-brain-planning-control',
        'humanoid-physical-ai/human-robot-interaction',
        'humanoid-physical-ai/real-world-applications',
        'humanoid-physical-ai/safety-ethics-and-future',
      ],
    },
  ],
};

export default sidebars;
